services:
  - type: web
    name: reparto-alfajores
    runtime: docker
    dockerfilePath: ./RepartoAlfajores/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false        # pegar la connection string de Neon
      - key: Auth__PasswordHash
        sync: false        # SHA-256 de tu contraseña
      - key: NombreNegocio
        sync: false        # ej: "Mi Reparto de Dulces"
